// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glpwslksoxhjzvywhbil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdscHdzbGtzb3hoanp2eXdoYmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDMyNjIsImV4cCI6MjA3MTU3OTI2Mn0.JZ-pa4Jy42snxLPY3zdU4LqsciAxH2gZPWi2o2jBrSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});